PREFIX temporal: <http://swrl.stanford.edu/ontologies/built-ins/3.3/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT DATA {
	<{{cfg['url']}}> rdf:type owl:NamedIndividual ;
        rdf:type video:Video ;
        video:keywords "{{cfg['keywords']}}" ;
        temporal:owlduration "{{cfg['duration']}}"^^xsd:dayTimeDuration ;
        dcterms:title "{{cfg['title']}}" ;
        dcterms:description "{{cfg['description']}}" .
    {% for s in cfg['scenes'] %}
    <{{cfg['url']}}#t{{s['start']}},{{s['end']}}> rdf:type owl:NamedIndividual ;
        rdf:type video:Scene ;
        video:sceneFrom <{{cfg['url']}}> ;
        temporal:owlhasStartTime "{{s['start']}}"^^xsd:time ;
        temporal:owlhasFinishTime "{{s['end']}}"^^xsd:time ;
        {% for c in s['concepts'] %}
        video:depicts <{{c}}> ;
        {% endfor %}
        rdfs:label "{{s['label']}}" .
    {% endfor %}
}